// base image of node - node:20.0


// copy project structure into base image - copy . .


// npm i - install dependencies

// shell command  - /shared-path foler/


// CMD ['node', 'app.js']

// volume - mount our db container 